#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "../../../android-ndk-r11c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -I/include -B/lib -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "android-armv7"
  #define DATE "Wed May 18 17:56:33 CST 2016"
#endif
